### ISSUE TITLE
Is compared with stereo ROVIO?

### ISSUE THREAD

**Issue by pytorch1100** [lastflowers/envio#5]
Hello and thank you for your excellent work! I would like to ask if the envio is compared to the stereo ROVIO?

**Comment by lastflowers** [comment]
Hi, thanks for having an interest in our work :)
We have compared ours to stereo ROVIO in our paper. Please check it for more details.

**Comment by pytorch1100** [comment]
Thank you for your very prompt reply! I can run through your code fine, but the stereo ROVIO I can't run through correctly. The dataset used is MH 01. Therefore, I would like to ask if you have modified the code for stereo ROVIO? If so, can you provide me with the following version of your stereo ROVIO! Thank you very much!

**Comment by lastflowers** [comment]
Hi, I am not sure what kind of problem you have, but if you did not check issues in the original ROVIO repo, take a look at this.
https://github.com/ethz-asl/rovio/issues/87

In my case, I modified the info file: 'useCrossCameraMeasurements false' as suggested by the author, extrinsic and IMU noise parameters according to my sensor.
