### ISSUE TITLE
For RGBD-mode

### ISSUE THREAD

**Issue by jiejie567** [lastflowers/envio#7]
Envio is definitely a treasure trove job, and I have shared it with all my SLAM buddies. I want to change it to RGB-D mode. Do you think this is convenient to implement？Thank you for your open-sorurce.

**Comment by lastflowers** [comment]
Hi, thanks for your interest in our work!

The current implementation of EnVIO is based on a stereo camera where only the left camera is used for photometric error minimization and the stereo baseline estimates the initial depth for each feature. Therefore, I think RGB-D would be compatible with elaborate modifications in our source code. It would be interesting to see EnVIO can work with a RGB-D sensor.

**Comment by jiejie567** [comment]
@lastflowers Thank you for your response. I have made the necessary adjustments and can confirm that I am able to use it without any issues. However, I would like to note that the accuracy of the RGB-D mode I am using may be lower compared to the stereo mode due to its roller shutter technology, as opposed to a global shutter.

**Comment by lastflowers** [comment]
Hi, I am happy that you managed to implement it using an RGB-D sensor. 
As you mentioned, I agree that the rolling shutter can be one of the reasons for the lower accuracy, since our code assumes a global shutter camera.

**Comment by jiejie567** [comment]
Thanks, looking forward to more of your excellent works!

**Comment by jiejie567** [comment]
if (is_valid) {
            cov_marg.block(0, cnt_c, cov_marg.rows(), 1) =
                cov_r_marg.block(0, c, cov_r_marg.cols(), 1);
            cnt_c ++;
        }
hi~,are there some problems in above code in sl_iekf.cpp ?
I think it is supposed to change " cov_r_marg.block(0, c, cov_r_marg.cols(), 1);" to "cov_r_marg.block(0, c, cov_r_marg.rows(), 1);"
I'm not very sure I'm right. I look forward to your reply. Thanks in advance.

**Comment by lastflowers** [comment]
Thanks for your point. Indeed you are right, it should be *.rows().
It didn't pose a problem because Eigen automatically adjusts proper dimension for the left hand side while running.

**Comment by jiejie567** [comment]
Thank you for reply and happy May day!





------------------ Original ------------------
From: Jaehyung Jung ***@***.***&gt;
Date: Tue,May 2,2023 0:18 PM
To: lastflowers/envio ***@***.***&gt;
Cc: jiejie567 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [lastflowers/envio] For RGBD-mode (Issue #7)

**Comment by lastflowers** [comment]
You too! Thanks for the fix :)
